# Generated by Django 5.2.12 on 2026-04-03 10:48

from django.db import migrations


def backfill_primary_participants(apps, schema_editor):
    Group = apps.get_model('core', 'Group')
    Participant = apps.get_model('core', 'Participant')

    for group in Group.objects.all():
        if Participant.objects.filter(group=group, is_primary=True).exists():
            continue

        owner = group.owner
        owner_name_candidates = []
        if owner:
            full_name = (f"{owner.first_name} {owner.last_name}").strip()
            if full_name:
                owner_name_candidates.append(full_name)
            if owner.email:
                owner_name_candidates.append(owner.email)
            if owner.username:
                owner_name_candidates.append(owner.username)

        participant = None
        if owner_name_candidates:
            participant = Participant.objects.filter(
                group=group,
                name__in=owner_name_candidates,
            ).first()

        if not participant:
            participant = Participant.objects.filter(group=group).order_by('created_at').first()

        if participant:
            participant.is_primary = True
            if owner:
                participant.user_id = owner.id
            participant.save(update_fields=['is_primary', 'user'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_participant_primary_user'),
    ]

    operations = [
        migrations.RunPython(backfill_primary_participants, migrations.RunPython.noop),
    ]
